[package]
name = "betterfield4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimp3 = "0.5.1"
pixels = "0.12.0"
rodio = "0.17.1"
